[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.supabase]
command = "npx"
args = ["-y", "supabase-mcp@latest", "supabase-mcp-claude"]
env = {
  SUPABASE_URL = "http://localhost",
  SUPABASE_ANON_KEY = "dummy",
  SUPABASE_SERVICE_ROLE_KEY = "replace-with-service-role",
  MCP_API_KEY = "local-dev-mcp"
}
