/**
 * This file is auto-generated by scripts/upload-local-content.ts
 * Do not edit manually.
 */

export const remoteManifest = {
  "hero/fd15a80f-1642-4cba-b214-9b6e5540ffd9 (1).mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/fd15a80f-1642-4cba-b214-9b6e5540ffd9-1.mp4",
    "path": "hero/fd15a80f-1642-4cba-b214-9b6e5540ffd9-1.mp4",
    "uploadedAt": "2025-11-04T08:30:01.738Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/dead94ae-be27-402b-b508-446ab4906355.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/dead94ae-be27-402b-b508-446ab4906355.mp4",
    "path": "hero/dead94ae-be27-402b-b508-446ab4906355.mp4",
    "uploadedAt": "2025-11-04T08:30:01.739Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/1a66d074-6607-4702-b631-7b2eaa99c5f4 (1).mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/1a66d074-6607-4702-b631-7b2eaa99c5f4-1.mp4",
    "path": "hero/1a66d074-6607-4702-b631-7b2eaa99c5f4-1.mp4",
    "uploadedAt": "2025-11-04T08:30:01.775Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/70c018d8-c093-4315-84ce-0f35b8029766.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/70c018d8-c093-4315-84ce-0f35b8029766.mp4",
    "path": "hero/70c018d8-c093-4315-84ce-0f35b8029766.mp4",
    "uploadedAt": "2025-11-04T08:30:01.889Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4",
    "path": "hero/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4",
    "uploadedAt": "2025-11-04T08:30:02.015Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251001_Image_to_Video_水_飲__4030_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/kling_20251001_Image_to_Video_-_-__4030_0.mp4",
    "path": "hero/kling_20251001_Image_to_Video_-_-__4030_0.mp4",
    "uploadedAt": "2025-11-04T08:30:02.057Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251003_Image_to_Video__腹_脂肪_手_揺__5216_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/kling_20251003_Image_to_Video__-_-_-_-__5216_0.mp4",
    "path": "hero/kling_20251003_Image_to_Video__-_-_-_-__5216_0.mp4",
    "uploadedAt": "2025-11-04T08:30:02.061Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251003_Image_to_Video_苦____上半身_起_5318_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/kling_20251003_Image_to_Video_-____-_-_5318_0.mp4",
    "path": "hero/kling_20251003_Image_to_Video_-____-_-_5318_0.mp4",
    "uploadedAt": "2025-11-04T08:30:02.077Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251006_Image_to_Video_水_飲_猫_2323_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/kling_20251006_Image_to_Video_-_-_-_2323_0.mp4",
    "path": "hero/kling_20251006_Image_to_Video_-_-_-_2323_0.mp4",
    "uploadedAt": "2025-11-04T08:30:02.111Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4",
    "path": "hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4",
    "uploadedAt": "2025-11-04T08:30:02.326Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/髪_載__手_上__下_____1751865480379.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/_-__-_-__-_____1751865480379.mp4",
    "path": "hero/_-__-_-__-_____1751865480379.mp4",
    "uploadedAt": "2025-11-04T08:30:02.380Z",
    "size": 60116,
    "mimeType": "video/mp4"
  },
  "hero/lifestyle_01.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/hero/lifestyle_01.mp4",
    "path": "hero/lifestyle_01.mp4",
    "uploadedAt": "2025-11-04T08:30:02.840Z",
    "size": 60116,
    "mimeType": "video/mp4"
  }
} as const;

export type RemoteManifest = typeof remoteManifest;
export type RemoteManifestEntry = RemoteManifest[keyof RemoteManifest];
