/**
 * This file is auto-generated by scripts/upload-watermarked-folder.ts
 * Do not edit manually.
 */

export const remoteManifest = {
  "lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5-wm-alpha200.mp4",
    "path": "lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:40.633Z",
    "size": 7322036,
    "mimeType": "video/mp4"
  },
  "lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7-wm-alpha200.mp4",
    "path": "lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:41.561Z",
    "size": 10011005,
    "mimeType": "video/mp4"
  },
  "lp-grid/330dd817-23ae-4db9-b0b6-753db5066976-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/330dd817-23ae-4db9-b0b6-753db5066976-wm-alpha200.mp4",
    "path": "lp-grid/330dd817-23ae-4db9-b0b6-753db5066976-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:42.360Z",
    "size": 6252620,
    "mimeType": "video/mp4"
  },
  "lp-grid/3a0cd595-e030-4a87-be61-5cb953d0d389-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/3a0cd595-e030-4a87-be61-5cb953d0d389-wm-alpha200.mp4",
    "path": "lp-grid/3a0cd595-e030-4a87-be61-5cb953d0d389-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:43.360Z",
    "size": 9972196,
    "mimeType": "video/mp4"
  },
  "lp-grid/46f2d754-00ab-445c-babe-262babef73f8-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/46f2d754-00ab-445c-babe-262babef73f8-wm-alpha200.mp4",
    "path": "lp-grid/46f2d754-00ab-445c-babe-262babef73f8-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:44.511Z",
    "size": 15652019,
    "mimeType": "video/mp4"
  },
  "lp-grid/a5ffd05a-7056-40ed-b2c0-3a8398a67eb8-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/a5ffd05a-7056-40ed-b2c0-3a8398a67eb8-wm-alpha200.mp4",
    "path": "lp-grid/a5ffd05a-7056-40ed-b2c0-3a8398a67eb8-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:45.460Z",
    "size": 10746810,
    "mimeType": "video/mp4"
  },
  "lp-grid/ad1fb127-40a1-4de0-be95-faddac4101bb-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/ad1fb127-40a1-4de0-be95-faddac4101bb-wm-alpha200.mp4",
    "path": "lp-grid/ad1fb127-40a1-4de0-be95-faddac4101bb-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:46.431Z",
    "size": 8651714,
    "mimeType": "video/mp4"
  },
  "lp-grid/dc14f10c-5207-4b08-a0df-516515283093-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/dc14f10c-5207-4b08-a0df-516515283093-wm-alpha200.mp4",
    "path": "lp-grid/dc14f10c-5207-4b08-a0df-516515283093-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:47.026Z",
    "size": 6720006,
    "mimeType": "video/mp4"
  },
  "lp-grid/fa08d950-cf7c-4e44-b486-46e447cd10dd (1)-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/fa08d950-cf7c-4e44-b486-46e447cd10dd-1-wm-alpha200.mp4",
    "path": "lp-grid/fa08d950-cf7c-4e44-b486-46e447cd10dd-1-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:47.702Z",
    "size": 8143935,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251001_Image_to_Video_She_raises_3933_0-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/kling_20251001_Image_to_Video_She_raises_3933_0-wm-alpha200.mp4",
    "path": "lp-grid/kling_20251001_Image_to_Video_She_raises_3933_0-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:48.077Z",
    "size": 4432722,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251001_Image_to_Video______仲良_散歩_3904_0-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/kling_20251001_Image_to_Video______-_-_3904_0-wm-alpha200.mp4",
    "path": "lp-grid/kling_20251001_Image_to_Video______-_-_3904_0-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:48.889Z",
    "size": 10969027,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251001_Image_to_Video_後__向___頭_左_3882_0-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/kling_20251001_Image_to_Video_-__-___-_-_3882_0-wm-alpha200.mp4",
    "path": "lp-grid/kling_20251001_Image_to_Video_-__-___-_-_3882_0-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:49.725Z",
    "size": 7749218,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251005_Image_to_Video_階段_昇_女性_2970_0-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/kling_20251005_Image_to_Video_-_-_-_2970_0-wm-alpha200.mp4",
    "path": "lp-grid/kling_20251005_Image_to_Video_-_-_-_2970_0-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:50.461Z",
    "size": 7042017,
    "mimeType": "video/mp4"
  },
  "lp-grid/_______食__喜___1753457904851-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/_______-__-___1753457904851-wm-alpha200.mp4",
    "path": "lp-grid/_______-__-___1753457904851-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:51.156Z",
    "size": 7753892,
    "mimeType": "video/mp4"
  },
  "lp-grid/手_位置______微笑___女性1753259534120-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/_-______-___-1753259534120-wm-alpha200.mp4",
    "path": "lp-grid/_-______-___-1753259534120-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:51.927Z",
    "size": 7372409,
    "mimeType": "video/mp4"
  },
  "lp-grid/片手__腹_脂肪_揺__女性1753257155150-wm-alpha200.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content/lp-grid/__-_-_-__-1753257155150-wm-alpha200.mp4",
    "path": "lp-grid/__-_-_-__-1753257155150-wm-alpha200.mp4",
    "uploadedAt": "2025-11-04T16:13:52.653Z",
    "size": 6910191,
    "mimeType": "video/mp4"
  }
} as const;

export type RemoteManifest = typeof remoteManifest;
export type RemoteManifestEntry = RemoteManifest[keyof RemoteManifest];
