/**
 * This file is auto-generated by scripts/upload-local-content.ts
 * Do not edit manually.
 */

export const remoteManifest = {
  "lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5.mp4",
    "path": "/lp-grid/0f831bc5-c64c-4f2b-8886-39ba7b8915d5.mp4",
    "uploadedAt": "2025-11-04T04:22:16.652Z",
    "size": 19478042,
    "mimeType": "video/mp4"
  },
  "lp-grid/d341b33e-3fa9-4ab8-a557-947312a29602.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/d341b33e-3fa9-4ab8-a557-947312a29602.mp4",
    "path": "/lp-grid/d341b33e-3fa9-4ab8-a557-947312a29602.mp4",
    "uploadedAt": "2025-11-04T04:22:17.260Z",
    "size": 17634439,
    "mimeType": "video/mp4"
  },
  "lp-grid/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4",
    "path": "/lp-grid/8ef984d0-acdf-4ccd-bce9-759db4d3714b.mp4",
    "uploadedAt": "2025-11-04T04:22:17.267Z",
    "size": 18355506,
    "mimeType": "video/mp4"
  },
  "lp-grid/d4c1a75f-81a8-41e5-8eca-6f3bf47d5056.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/d4c1a75f-81a8-41e5-8eca-6f3bf47d5056.mp4",
    "path": "/lp-grid/d4c1a75f-81a8-41e5-8eca-6f3bf47d5056.mp4",
    "uploadedAt": "2025-11-04T04:22:17.415Z",
    "size": 25454770,
    "mimeType": "video/mp4"
  },
  "lp-grid/a76adf72-c107-42d4-ab11-3a75bfa95677.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/a76adf72-c107-42d4-ab11-3a75bfa95677.mp4",
    "path": "/lp-grid/a76adf72-c107-42d4-ab11-3a75bfa95677.mp4",
    "uploadedAt": "2025-11-04T04:22:17.722Z",
    "size": 23610534,
    "mimeType": "video/mp4"
  },
  "lp-grid/4c51490a-c391-4ff5-b4e1-132de3e9e0e9.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/4c51490a-c391-4ff5-b4e1-132de3e9e0e9.mp4",
    "path": "/lp-grid/4c51490a-c391-4ff5-b4e1-132de3e9e0e9.mp4",
    "uploadedAt": "2025-11-04T04:22:17.788Z",
    "size": 18387916,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251005_Image_to_Video_階段_昇_女性_2970_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/kling_20251005_Image_to_Video_-_-_-_2970_0.mp4",
    "path": "/lp-grid/kling_20251005_Image_to_Video_-_-_-_2970_0.mp4",
    "uploadedAt": "2025-11-04T04:22:17.958Z",
    "size": 19732535,
    "mimeType": "video/mp4"
  },
  "lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7.mp4",
    "path": "/lp-grid/2ae957e8-a3e4-421e-8b6c-a091d861f2c7.mp4",
    "uploadedAt": "2025-11-04T04:22:18.098Z",
    "size": 24497566,
    "mimeType": "video/mp4"
  },
  "lp-grid/70c018d8-c093-4315-84ce-0f35b8029766.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/70c018d8-c093-4315-84ce-0f35b8029766.mp4",
    "path": "/lp-grid/70c018d8-c093-4315-84ce-0f35b8029766.mp4",
    "uploadedAt": "2025-11-04T04:22:18.211Z",
    "size": 24926970,
    "mimeType": "video/mp4"
  },
  "lp-grid/____変___微笑_1753633665589.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/____-___-_1753633665589.mp4",
    "path": "/lp-grid/____-___-_1753633665589.mp4",
    "uploadedAt": "2025-11-04T04:22:18.710Z",
    "size": 5620831,
    "mimeType": "video/mp4"
  },
  "lp-grid/____変___微笑_1753633908487.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/____-___-_1753633908487.mp4",
    "path": "/lp-grid/____-___-_1753633908487.mp4",
    "uploadedAt": "2025-11-04T04:22:18.892Z",
    "size": 11270892,
    "mimeType": "video/mp4"
  },
  "hero/5a2a8dfa-f457-46d3-a0bf-dafdc24b081c.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/5a2a8dfa-f457-46d3-a0bf-dafdc24b081c.mp4",
    "path": "/hero/5a2a8dfa-f457-46d3-a0bf-dafdc24b081c.mp4",
    "uploadedAt": "2025-11-04T04:22:19.104Z",
    "size": 7880953,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251006_Image_to_Video________食___2841_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/kling_20251006_Image_to_Video________-___2841_0.mp4",
    "path": "/lp-grid/kling_20251006_Image_to_Video________-___2841_0.mp4",
    "uploadedAt": "2025-11-04T04:22:19.204Z",
    "size": 19155015,
    "mimeType": "video/mp4"
  },
  "lp-grid/_____細________女性1753257682556.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/_____-________-1753257682556.mp4",
    "path": "/lp-grid/_____-________-1753257682556.mp4",
    "uploadedAt": "2025-11-04T04:22:19.382Z",
    "size": 16910510,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251006_Image_to_Video_携帯_見_笑顔____2832_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/kling_20251006_Image_to_Video_-_-_-____2832_0.mp4",
    "path": "/lp-grid/kling_20251006_Image_to_Video_-_-_-____2832_0.mp4",
    "uploadedAt": "2025-11-04T04:22:19.387Z",
    "size": 19478925,
    "mimeType": "video/mp4"
  },
  "lp-grid/kling_20251006_Image_to_Video_可愛_笑顔_女性_2798_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/kling_20251006_Image_to_Video_-_-_-_2798_0.mp4",
    "path": "/lp-grid/kling_20251006_Image_to_Video_-_-_-_2798_0.mp4",
    "uploadedAt": "2025-11-04T04:22:19.406Z",
    "size": 17706447,
    "mimeType": "video/mp4"
  },
  "hero/kling_20250830_Image_to_Video_Men_concer_3121_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/kling_20250830_Image_to_Video_Men_concer_3121_0.mp4",
    "path": "/hero/kling_20250830_Image_to_Video_Men_concer_3121_0.mp4",
    "uploadedAt": "2025-11-04T04:22:19.429Z",
    "size": 2481404,
    "mimeType": "video/mp4"
  },
  "hero/998a302e-eb19-4a62-a721-59efab8b44f7.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/998a302e-eb19-4a62-a721-59efab8b44f7.mp4",
    "path": "/hero/998a302e-eb19-4a62-a721-59efab8b44f7.mp4",
    "uploadedAt": "2025-11-04T04:22:19.522Z",
    "size": 5842624,
    "mimeType": "video/mp4"
  },
  "lp-grid/手_位置______微笑___女性1753259534120.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//lp-grid/_-______-___-1753259534120.mp4",
    "path": "/lp-grid/_-______-___-1753259534120.mp4",
    "uploadedAt": "2025-11-04T04:22:19.625Z",
    "size": 17894088,
    "mimeType": "video/mp4"
  },
  "hero/605b42f3-719e-480f-9e5c-1614dee6bf3c.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/605b42f3-719e-480f-9e5c-1614dee6bf3c.mp4",
    "path": "/hero/605b42f3-719e-480f-9e5c-1614dee6bf3c.mp4",
    "uploadedAt": "2025-11-04T04:22:19.754Z",
    "size": 10886338,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251004_Image_to_Video_水_飲_女性_4206_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/kling_20251004_Image_to_Video_-_-_-_4206_0.mp4",
    "path": "/hero/kling_20251004_Image_to_Video_-_-_-_4206_0.mp4",
    "uploadedAt": "2025-11-04T04:22:19.857Z",
    "size": 5500168,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251006_Image_to_Video_苦____表情_腹筋_3203_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/kling_20251006_Image_to_Video_-____-_-_3203_0.mp4",
    "path": "/hero/kling_20251006_Image_to_Video_-____-_-_3203_0.mp4",
    "uploadedAt": "2025-11-04T04:22:20.025Z",
    "size": 4367649,
    "mimeType": "video/mp4"
  },
  "hero/____変___微笑_1753634078225.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/____-___-_1753634078225.mp4",
    "path": "/hero/____-___-_1753634078225.mp4",
    "uploadedAt": "2025-11-04T04:22:20.147Z",
    "size": 6381094,
    "mimeType": "video/mp4"
  },
  "hero/片手_歯_磨___女性1753261368538.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/_-_-___-1753261368538.mp4",
    "path": "/hero/_-_-___-1753261368538.mp4",
    "uploadedAt": "2025-11-04T04:22:20.415Z",
    "size": 7334560,
    "mimeType": "video/mp4"
  },
  "hero/kling_20251006_Image_to_Video_綺麗_肌_自慢__女_2793_0.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/kling_20251006_Image_to_Video_-_-_-__-_2793_0.mp4",
    "path": "/hero/kling_20251006_Image_to_Video_-_-_-__-_2793_0.mp4",
    "uploadedAt": "2025-11-04T04:22:20.546Z",
    "size": 6858275,
    "mimeType": "video/mp4"
  },
  "hero/髪_載__手_上__下_____1751865480379.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/_-__-_-__-_____1751865480379.mp4",
    "path": "/hero/_-__-_-__-_____1751865480379.mp4",
    "uploadedAt": "2025-11-04T04:22:20.581Z",
    "size": 6976060,
    "mimeType": "video/mp4"
  },
  "hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4": {
    "url": "https://xwwvjoqiicwrjzvzjqju.supabase.co/storage/v1/object/public/local-content//hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4",
    "path": "/hero/Masterpiece__top_quality__ultra_detailed__photorealistic__4K__cinematic_shot__shallow_d1752043157362.mp4",
    "uploadedAt": "2025-11-04T04:22:20.603Z",
    "size": 6674090,
    "mimeType": "video/mp4"
  }
} as const;

export type RemoteManifest = typeof remoteManifest;
export type RemoteManifestEntry = RemoteManifest[keyof RemoteManifest];
